language: php
php:
  - 7.1
  - 7.2
install:
  - composer require codeclimate/php-test-reporter --dev
  - composer install --no-interaction
before_script:
  - composer self-update
  - composer install
notifications:
  email: false
script: 
  - ./vendor/bin/phpunit
addons:
  code_climate:
    repo_token: b2e2b1d897384817a588f5de1249dfd0f28eff80408feddc54b9d8f7effc615c
after_success:
  - php vendor/bin/coveralls -v
  - vendor/bin/test-reporter
